### ISSUE TITLE
issue: commisery does not pick up .commisery.yml config filee

### ISSUE THREAD

**Issue by dzhemaptula-tomtom** [tomtom-international/commisery-action#114]
We have added a .commisery.yml file in the root of our repo and are running the workflow action.
But it seems the config file is not being picked up.

Not sure if this is on our side.

Action:
```
name: Commisery
on:
  pull_request:

jobs:
  commit-message:
    name: Conventional Commit compliance
    runs-on: ubuntu-latest
    steps:
    - name: Check for compliance
      uses: tomtom-international/commisery-action@v2
      with:
        token: ${{ github.token }}
```

config:
```
max-subject-length: 100
disable:
  - C003
  - C016
```

error on ci:
```
Commit SHA (xxx): fix: updated testing
  error: [C016] The commit message's description should be written in imperative mood
  fix: updated testing
```
