### ISSUE TITLE
Question about `validate-commits: false` and `validate-pull-request: true`

### ISSUE THREAD

**Issue by oliverscherf-tomtom** [tomtom-international/commisery-action#255]
Hey!

We are using the `commisery-action` in our repository. Since we are thinking about stop allowing merge commits to main, we can also disable the checking of the commits on (feature) branches.

Our goal is to only check PR title and that the squash-commit resulting from a PR follows the commit conventions.

```
name: Commit-checker

on:
  workflow_call:

jobs:
  commisery:
    name: Check compliance with Conventional Commits
    steps:
      - uses: tomtom-international/commisery-action@v2
        with:
          validate-commits: false
          validate-pull-request: true
          token: ${{ github.token }}
```

Is this doing what I'm expecting:

- disable commit message checking on the feature branch
- keep verification of PR titles
- keep verification of commit message when I later squash-merge this PR

Thanks.
